from django.conf.urls import patterns
from django.conf.urls import url

urlpatterns = patterns('softGISview.views',
    url(r'^$', 
        'main',
        name='front_page'),
    url(r'^travel$', 
        'travel',
        name='travel'),
    url(r'^teacher$', 
        'get_school_list',
        name='teacher'),
    url(r'^school_data$', 
        'school_data',
        name='school_data'),
    url(r'^free_time$', 
        'get_free_time_features',
        name='free_time_feat'),
    url(r'^time_class$', 
        'get_time_classes',
        name='get_time_classes'),
    url(r'^screen_time', 
        'get_screen_times',
        name='screen_time'),
    #url(r'^school_journey$', 
    #    'journey',
    #    name='journey'),
    url(r'^content/(?P<file_type>\w+)/(?P<page_name>\w+)', 
        'subcontent',
        name='subcontent'),
)